openapi: 3.0.3
info:
  title: Divider Service
  description: An example illustrating error handling in goa. See docs/ErrorHandling.md.
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for divider
paths:
  /div/{a}/{b}:
    get:
      tags:
      - divider
      summary: divide divider
      operationId: divider#divide
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: number
          description: Left operand
          example: 0.5286530789660119
          format: double
        example: 0.8201805920455113
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: number
          description: Right operand
          example: 0.2097150078861952
          format: double
        example: 0.841081188964521
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: number
                example: 0.8096382349832494
                format: double
              example: 0.04845026310987674
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "504":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /idiv/{a}/{b}:
    get:
      tags:
      - divider
      summary: integer_divide divider
      operationId: divider#integer_divide
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: integer
          description: Left operand
          example: 1507115647399647933
          format: int64
        example: 6789275876984930452
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: integer
          description: Right operand
          example: 445260288755784518
          format: int64
        example: 3219628185476174303
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: integer
                example: 7567882148725513218
                format: int64
              example: 3100890898189865870
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "417":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "504":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
components:
  schemas:
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: true
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      description: integer division has remainder
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
