swagger: "2.0"
info:
  title: Chatter service describing the streaming features of goa v2.
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /echoer:
    get:
      tags:
      - chatter
      summary: echoer chatter
      description: |-
        Echoes the message sent by the client.

        **Required security scopes for jwt**:
          * `stream:write`
      operationId: chatter#echoer
      parameters:
      - name: Authorization
        in: header
        description: JWT used for authentication
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ChatterEchoerUnauthorizedResponseBody'
        "403":
          description: Forbidden response.
          schema:
            $ref: '#/definitions/ChatterEchoerInvalidScopesResponseBody'
      schemes:
      - ws
      security:
      - jwt_header_Authorization: []
  /history:
    get:
      tags:
      - chatter
      summary: history chatter
      description: |-
        Returns the chat messages sent to the server.

        **Required security scopes for jwt**:
          * `stream:read`
      operationId: chatter#history
      parameters:
      - name: view
        in: query
        description: View to use to render the result
        required: false
        type: string
      - name: Authorization
        in: header
        description: JWT used for authentication
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols response.
          schema:
            $ref: '#/definitions/ChatterHistoryResponseBody'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ChatterHistoryUnauthorizedResponseBody'
        "403":
          description: Forbidden response.
          schema:
            $ref: '#/definitions/ChatterHistoryInvalidScopesResponseBody'
      schemes:
      - ws
      security:
      - jwt_header_Authorization: []
  /listener:
    get:
      tags:
      - chatter
      summary: listener chatter
      description: |-
        Listens to the messages sent by the client.

        **Required security scopes for jwt**:
          * `stream:write`
      operationId: chatter#listener
      parameters:
      - name: Authorization
        in: header
        description: JWT used for authentication
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ChatterListenerUnauthorizedResponseBody'
        "403":
          description: Forbidden response.
          schema:
            $ref: '#/definitions/ChatterListenerInvalidScopesResponseBody'
      schemes:
      - ws
      security:
      - jwt_header_Authorization: []
  /login:
    post:
      tags:
      - chatter
      summary: login chatter
      description: Creates a valid JWT token for auth to chat.
      operationId: chatter#login
      parameters:
      - name: Authorization
        in: header
        description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ChatterLoginUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - basic_header_Authorization: []
  /subscribe:
    get:
      tags:
      - chatter
      summary: subscribe chatter
      description: |-
        Subscribe to events sent when new chat messages are added.

        **Required security scopes for jwt**:
          * `stream:write`
      operationId: chatter#subscribe
      parameters:
      - name: Authorization
        in: header
        description: JWT used for authentication
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols response.
          schema:
            $ref: '#/definitions/ChatterSubscribeResponseBody'
            required:
            - message
            - action
            - added_at
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ChatterSubscribeUnauthorizedResponseBody'
        "403":
          description: Forbidden response.
          schema:
            $ref: '#/definitions/ChatterSubscribeInvalidScopesResponseBody'
      schemes:
      - ws
      security:
      - jwt_header_Authorization: []
  /summary:
    get:
      tags:
      - chatter
      summary: summary chatter
      description: |-
        Summarizes the chat messages sent by the client.

        **Required security scopes for jwt**:
          * `stream:write`
      operationId: chatter#summary
      parameters:
      - name: Authorization
        in: header
        description: JWT used for authentication
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols response.
          schema:
            $ref: '#/definitions/ChatterChatSummaryResponseCollection'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ChatterSummaryUnauthorizedResponseBody'
        "403":
          description: Forbidden response.
          schema:
            $ref: '#/definitions/ChatterSummaryInvalidScopesResponseBody'
      schemes:
      - ws
      security:
      - jwt_header_Authorization: []
definitions:
  ChatSummaryResponse:
    title: 'Mediatype identifier: application/vnd.goa.summary; view=default'
    type: object
    properties:
      length:
        type: integer
        description: Length of the message sent
        example: 3756131783218505890
        format: int64
      message:
        type: string
        description: Message sent to the server
        example: Veritatis veritatis soluta qui at et eius.
      sent_at:
        type: string
        description: Time at which the message was sent
        example: "1976-12-29T13:56:34Z"
        format: date-time
    description: ChatSummaryResponse result type (default view)
    example:
      length: 2056634801561563523
      message: Magni doloribus at nam ipsum soluta.
      sent_at: "1998-03-22T14:13:38Z"
    required:
    - message
    - sent_at
  ChatterChatSummaryResponseCollection:
    title: 'Mediatype identifier: application/vnd.goa.summary; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/ChatSummaryResponse'
    description: SummaryResponseBody is the result type for an array of ChatSummaryResponse
      (default view)
    example:
    - length: 4832953061930875130
      message: Molestiae autem voluptatem voluptate autem incidunt.
      sent_at: "1970-05-07T05:21:01Z"
    - length: 4832953061930875130
      message: Molestiae autem voluptatem voluptate autem incidunt.
      sent_at: "1970-05-07T05:21:01Z"
  ChatterEchoerInvalidScopesResponseBody:
    title: ChatterEchoerInvalidScopesResponseBody
    type: string
    example: Earum omnis incidunt sequi accusantium illum.
  ChatterEchoerUnauthorizedResponseBody:
    title: ChatterEchoerUnauthorizedResponseBody
    type: string
    example: Tempora repudiandae ipsa aut.
  ChatterHistoryInvalidScopesResponseBody:
    title: ChatterHistoryInvalidScopesResponseBody
    type: string
    example: Sit id.
  ChatterHistoryResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.summary; view=default'
    type: object
    properties:
      length:
        type: integer
        description: Length of the message sent
        example: 632493872526913854
        format: int64
      message:
        type: string
        description: Message sent to the server
        example: Qui veritatis illo ea non voluptatum.
      sent_at:
        type: string
        description: Time at which the message was sent
        example: "2013-02-14T14:12:04Z"
        format: date-time
    description: HistoryResponseBody result type (default view)
    example:
      length: 5024516386033482824
      message: Qui illo porro quia.
      sent_at: "1982-12-04T07:28:35Z"
    required:
    - message
    - sent_at
  ChatterHistoryUnauthorizedResponseBody:
    title: ChatterHistoryUnauthorizedResponseBody
    type: string
    example: Aut quae quis et natus et.
  ChatterListenerInvalidScopesResponseBody:
    title: ChatterListenerInvalidScopesResponseBody
    type: string
    example: Consequatur rerum.
  ChatterListenerUnauthorizedResponseBody:
    title: ChatterListenerUnauthorizedResponseBody
    type: string
    example: Suscipit ut saepe consequuntur rerum ut et.
  ChatterLoginUnauthorizedResponseBody:
    title: ChatterLoginUnauthorizedResponseBody
    type: string
    description: Credentials are invalid
    example: Suscipit officiis odit dolor dolorum reprehenderit dolorum.
  ChatterSubscribeInvalidScopesResponseBody:
    title: ChatterSubscribeInvalidScopesResponseBody
    type: string
    example: Iure aperiam modi.
  ChatterSubscribeResponseBody:
    title: ChatterSubscribeResponseBody
    type: object
    properties:
      action:
        type: string
        example: added
        enum:
        - added
      added_at:
        type: string
        description: Time at which the message was added
        example: "2014-04-06T02:17:21Z"
        format: date-time
      message:
        type: string
        description: Message sent to the server
        example: Necessitatibus dolorem.
    example:
      action: added
      added_at: "1985-05-22T04:05:28Z"
      message: Nisi ut autem nobis ad.
    required:
    - message
    - action
    - added_at
  ChatterSubscribeUnauthorizedResponseBody:
    title: ChatterSubscribeUnauthorizedResponseBody
    type: string
    example: Dolore commodi eos omnis est qui.
  ChatterSummaryInvalidScopesResponseBody:
    title: ChatterSummaryInvalidScopesResponseBody
    type: string
    example: Aut velit.
  ChatterSummaryUnauthorizedResponseBody:
    title: ChatterSummaryUnauthorizedResponseBody
    type: string
    example: Veritatis temporibus.
securityDefinitions:
  basic_header_Authorization:
    type: basic
    description: Secures the login endpoint.
  jwt_header_Authorization:
    type: apiKey
    description: |-
      Secures endpoint by requiring a valid JWT token. Supports scopes "stream:read" and "stream:write".

      **Security Scopes**:
        * `stream:read`: Read-only access
        * `stream:write`: Read and write access
    name: Authorization
    in: header
