swagger: "2.0"
info:
  title: Chatter service describing the streaming features of goa v2.
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /echoer:
    get:
      tags:
      - chatter
      summary: echoer chatter
      description: |-
        Echoes the message sent by the client.

        **Required security scopes for jwt**:
          * `stream:write`
      operationId: chatter#echoer
      parameters:
      - name: Authorization
        in: header
        description: JWT used for authentication
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ChatterEchoerUnauthorizedResponseBody'
        "403":
          description: Forbidden response.
          schema:
            $ref: '#/definitions/ChatterEchoerInvalidScopesResponseBody'
      schemes:
      - ws
      security:
      - jwt_header_Authorization: []
  /history:
    get:
      tags:
      - chatter
      summary: history chatter
      description: |-
        Returns the chat messages sent to the server.

        **Required security scopes for jwt**:
          * `stream:read`
      operationId: chatter#history
      parameters:
      - name: view
        in: query
        description: View to use to render the result
        required: false
        type: string
      - name: Authorization
        in: header
        description: JWT used for authentication
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols response.
          schema:
            $ref: '#/definitions/ChatterHistoryResponseBody'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ChatterHistoryUnauthorizedResponseBody'
        "403":
          description: Forbidden response.
          schema:
            $ref: '#/definitions/ChatterHistoryInvalidScopesResponseBody'
      schemes:
      - ws
      security:
      - jwt_header_Authorization: []
  /listener:
    get:
      tags:
      - chatter
      summary: listener chatter
      description: |-
        Listens to the messages sent by the client.

        **Required security scopes for jwt**:
          * `stream:write`
      operationId: chatter#listener
      parameters:
      - name: Authorization
        in: header
        description: JWT used for authentication
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ChatterListenerUnauthorizedResponseBody'
        "403":
          description: Forbidden response.
          schema:
            $ref: '#/definitions/ChatterListenerInvalidScopesResponseBody'
      schemes:
      - ws
      security:
      - jwt_header_Authorization: []
  /login:
    post:
      tags:
      - chatter
      summary: login chatter
      description: Creates a valid JWT token for auth to chat.
      operationId: chatter#login
      parameters:
      - name: Authorization
        in: header
        description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ChatterLoginUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - basic_header_Authorization: []
  /subscribe:
    get:
      tags:
      - chatter
      summary: subscribe chatter
      description: |-
        Subscribe to events sent when new chat messages are added.

        **Required security scopes for jwt**:
          * `stream:write`
      operationId: chatter#subscribe
      parameters:
      - name: Authorization
        in: header
        description: JWT used for authentication
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols response.
          schema:
            $ref: '#/definitions/ChatterSubscribeResponseBody'
            required:
            - message
            - action
            - added_at
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ChatterSubscribeUnauthorizedResponseBody'
        "403":
          description: Forbidden response.
          schema:
            $ref: '#/definitions/ChatterSubscribeInvalidScopesResponseBody'
      schemes:
      - ws
      security:
      - jwt_header_Authorization: []
  /summary:
    get:
      tags:
      - chatter
      summary: summary chatter
      description: |-
        Summarizes the chat messages sent by the client.

        **Required security scopes for jwt**:
          * `stream:write`
      operationId: chatter#summary
      parameters:
      - name: Authorization
        in: header
        description: JWT used for authentication
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols response.
          schema:
            $ref: '#/definitions/ChatterChatSummaryResponseCollection'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ChatterSummaryUnauthorizedResponseBody'
        "403":
          description: Forbidden response.
          schema:
            $ref: '#/definitions/ChatterSummaryInvalidScopesResponseBody'
      schemes:
      - ws
      security:
      - jwt_header_Authorization: []
definitions:
  ChatSummaryResponse:
    title: 'Mediatype identifier: application/vnd.goa.summary; view=default'
    type: object
    properties:
      length:
        type: integer
        description: Length of the message sent
        example: 2203331266328453673
        format: int64
      message:
        type: string
        description: Message sent to the server
        example: Nemo maxime.
      sent_at:
        type: string
        description: Message sent to the server
        example: Dignissimos qui.
    description: ChatSummaryResponse result type (default view)
    example:
      length: 250693181101823335
      message: Et omnis consectetur suscipit.
      sent_at: Dolor dolorum reprehenderit dolorum voluptas tempora repudiandae.
    required:
    - message
    - sent_at
  ChatterChatSummaryResponseCollection:
    title: 'Mediatype identifier: application/vnd.goa.summary; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/ChatSummaryResponse'
    description: SummaryResponseBody is the result type for an array of ChatSummaryResponse
      (default view)
    example:
    - length: 4832953061930875130
      message: Molestiae autem voluptatem voluptate autem incidunt.
      sent_at: Eos est sed impedit ut similique tempora.
    - length: 4832953061930875130
      message: Molestiae autem voluptatem voluptate autem incidunt.
      sent_at: Eos est sed impedit ut similique tempora.
    - length: 4832953061930875130
      message: Molestiae autem voluptatem voluptate autem incidunt.
      sent_at: Eos est sed impedit ut similique tempora.
  ChatterEchoerInvalidScopesResponseBody:
    title: ChatterEchoerInvalidScopesResponseBody
    type: string
    example: Eveniet repellendus eum aut ut.
  ChatterEchoerUnauthorizedResponseBody:
    title: ChatterEchoerUnauthorizedResponseBody
    type: string
    example: Commodi fugit sunt perferendis ducimus adipisci.
  ChatterHistoryInvalidScopesResponseBody:
    title: ChatterHistoryInvalidScopesResponseBody
    type: string
    example: Dolores voluptatem voluptas dolorem quibusdam reiciendis maxime.
  ChatterHistoryResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.summary; view=default'
    type: object
    properties:
      length:
        type: integer
        description: Length of the message sent
        example: 7779235888077241013
        format: int64
      message:
        type: string
        description: Message sent to the server
        example: Veritatis temporibus.
      sent_at:
        type: string
        description: Message sent to the server
        example: Velit veritatis necessitatibus dolorem aut nisi unde.
    description: HistoryResponseBody result type (default view)
    example:
      length: 4657703542569700382
      message: Et eius modi sit aspernatur.
      sent_at: Voluptas sint ipsam dolor odio molestias.
    required:
    - message
    - sent_at
  ChatterHistoryUnauthorizedResponseBody:
    title: ChatterHistoryUnauthorizedResponseBody
    type: string
    example: Aut inventore quia aut atque debitis harum.
  ChatterListenerInvalidScopesResponseBody:
    title: ChatterListenerInvalidScopesResponseBody
    type: string
    example: Fugiat autem molestiae incidunt vel nihil.
  ChatterListenerUnauthorizedResponseBody:
    title: ChatterListenerUnauthorizedResponseBody
    type: string
    example: Dolores nisi qui est accusamus veniam tenetur.
  ChatterLoginUnauthorizedResponseBody:
    title: ChatterLoginUnauthorizedResponseBody
    type: string
    description: Credentials are invalid
    example: Unde vero iure provident.
  ChatterSubscribeInvalidScopesResponseBody:
    title: ChatterSubscribeInvalidScopesResponseBody
    type: string
    example: Omnis aut.
  ChatterSubscribeResponseBody:
    title: ChatterSubscribeResponseBody
    type: object
    properties:
      action:
        type: string
        example: added
        enum:
        - added
      added_at:
        type: string
        description: Time at which the message was added
        example: "2007-09-03T16:26:40Z"
        format: date-time
      message:
        type: string
        description: Message sent to the server
        example: Ut saepe consequuntur rerum ut et velit.
    example:
      action: added
      added_at: "2009-02-17T11:28:06Z"
      message: Nam qui quas dignissimos qui ab.
    required:
    - message
    - action
    - added_at
  ChatterSubscribeUnauthorizedResponseBody:
    title: ChatterSubscribeUnauthorizedResponseBody
    type: string
    example: Doloremque nulla magni exercitationem perspiciatis.
  ChatterSummaryInvalidScopesResponseBody:
    title: ChatterSummaryInvalidScopesResponseBody
    type: string
    example: Illum in.
  ChatterSummaryUnauthorizedResponseBody:
    title: ChatterSummaryUnauthorizedResponseBody
    type: string
    example: Quaerat earum omnis incidunt sequi.
securityDefinitions:
  basic_header_Authorization:
    type: basic
    description: Secures the login endpoint.
  jwt_header_Authorization:
    type: apiKey
    description: |-
      Secures endpoint by requiring a valid JWT token. Supports scopes "stream:read" and "stream:write".

      **Security Scopes**:
        * `stream:read`: Read-only access
        * `stream:write`: Read and write access
    name: Authorization
    in: header
