language: go
dist: xenial
go:
- "1.14.x"

script:
- export PATH=${PATH}:${HOME}/bin:${HOME}/gopath/bin
- cd ../../.. && mkdir goa.design && cp -r github.com/goadesign/examples goa.design/examples
- cd goa.design/examples
- make travis
