consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
host: localhost:8080
info:
  title: Websocket echo server
  version: ""
paths:
  /echo:
    get:
      description: echo websocket server
      operationId: echo#connect
      parameters:
      - description: Initial message to echo
        in: query
        name: initial
        required: false
        type: string
      responses:
        "101":
          description: Switching Protocols
      schemes:
      - ws
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  SwitchingProtocols:
    description: Switching Protocols
schemes:
- http
swagger: "2.0"
